[project]
name = ""
version = ""
description = ""
authors = [
    {name = "MRSlou", email = "mrslouu@163.com"},
]
dependencies = [
    "bilibili-api-python>=16.1.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

